type AllCountryOption = {
  name: string;
  value: string;
  code: string;
};

const allCountryOptions: AllCountryOption[] = [
  { name: 'Albania', value: 'Albania', code: 'AL' },
  { name: 'Åland Islands', value: 'Åland Islands', code: 'AX' },
  { name: 'Algeria', value: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', value: 'American Samoa', code: 'AS' },
  { name: 'Andorra', value: 'Andorra', code: 'AD' },
  { name: 'Angola', value: 'Angola', code: 'AO' },
  { name: 'Anguilla', value: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', value: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', value: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', value: 'Argentina', code: 'AR' },
  { name: 'Armenia', value: 'Armenia', code: 'AM' },
  { name: 'Aruba', value: 'Aruba', code: 'AW' },
  { name: 'Australia', value: 'Australia', code: 'AU' },
  { name: 'Austria', value: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', value: 'Azerbaijan', code: 'AZ' },
  { name: 'The Bahamas', value: 'The Bahamas', code: 'BS' },
  { name: 'Bahrain', value: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', value: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', value: 'Barbados', code: 'BB' },
  { name: 'Belarus', value: 'Belarus', code: 'BY' },
  { name: 'Belgium', value: 'Belgium', code: 'BE' },
  { name: 'Belize', value: 'Belize', code: 'BZ' },
  { name: 'Benin', value: 'Benin', code: 'BJ' },
  { name: 'Bermuda', value: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', value: 'Bhutan', code: 'BT' },
  {
    name: 'Bolivia (Plurinational State of)',
    value: 'Bolivia (Plurinational State of)',
    code: 'BO',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    value: 'Bonaire, Sint Eustatius and Saba',
    code: 'BQ',
  },
  { name: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', value: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', value: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', value: 'Brazil', code: 'BR' },
  {
    name: 'The British Indian Ocean Territory',
    value: 'The British Indian Ocean Territory',
    code: 'IO',
  },
  { name: 'Brunei Darussalam', value: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', value: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', value: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', value: 'Burundi', code: 'BI' },
  { name: 'Cabo Verde', value: 'Cabo Verde', code: 'CV' },
  { name: 'Cambodia', value: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', value: 'Cameroon', code: 'CM' },
  { name: 'Canada', value: 'Canada', code: 'CA' },
  { name: 'The Cayman Islands', value: 'The Cayman Islands', code: 'KY' },
  { name: 'The Central African Republic', value: 'The Central African Republic', code: 'CF' },
  { name: 'Chad', value: 'Chad', code: 'TD' },
  { name: 'Chile', value: 'Chile', code: 'CL' },
  { name: 'China', value: 'China', code: 'CN' },
  { name: 'Christmas Island', value: 'Christmas Island', code: 'CX' },
  { name: 'The Cocos (Keeling) Islands', value: 'The Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', value: 'Colombia', code: 'CO' },
  { name: 'The Comoros', value: 'The Comoros', code: 'KM' },
  {
    name: 'Congo (the Democratic Republic of the)',
    value: 'Congo (the Democratic Republic of the)',
    code: 'CD',
  },
  { name: 'The Congo', value: 'The Congo', code: 'CG' },
  { name: 'The Cook Islands', value: 'The Cook Islands', code: 'CK' },
  { name: 'Costa Rica', value: 'Costa Rica', code: 'CR' },
  { name: 'Croatia', value: 'Croatia', code: 'HR' },
  { name: 'Cuba', value: 'Cuba', code: 'CU' },
  { name: 'Curaçao', value: 'Curaçao', code: 'CW' },
  { name: 'Cyprus', value: 'Cyprus', code: 'CY' },
  { name: 'Czechia', value: 'Czechia', code: 'CZ' },
  { name: "Côte d'Ivoire", value: "Côte d'Ivoire", code: 'CI' },
  { name: 'Denmark', value: 'Denmark', code: 'DK' },
  { name: 'Djibouti', value: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', value: 'Dominica', code: 'DM' },
  { name: 'The Dominican Republic', value: 'The Dominican Republic', code: 'DO' },
  { name: 'Ecuador', value: 'Ecuador', code: 'EC' },
  { name: 'Egypt', value: 'Egypt', code: 'EG' },
  { name: 'El Salvador', value: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', value: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', value: 'Eritrea', code: 'ER' },
  { name: 'Estonia', value: 'Estonia', code: 'EE' },
  { name: 'Eswatini', value: 'Eswatini', code: 'SZ' },
  { name: 'Ethiopia', value: 'Ethiopia', code: 'ET' },
  {
    name: 'The Falkland Islands (the) [Mal',
    value: 'The Falkland Islands (the) [Mal',
    code: 'FK',
  },
  { name: 'The Faroe Islands', value: 'The Faroe Islands', code: 'FO' },
  { name: 'Fiji', value: 'Fiji', code: 'FJ' },
  { name: 'Finland', value: 'Finland', code: 'FI' },
  { name: 'France', value: 'France', code: 'FR' },
  { name: 'French Guiana', value: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', value: 'French Polynesia', code: 'PF' },
  {
    name: 'The French Southern Territories',
    value: 'The French Southern Territories',
    code: 'TF',
  },
  { name: 'Gabon', value: 'Gabon', code: 'GA' },
  { name: 'The Gambia', value: 'The Gambia', code: 'GM' },
  { name: 'Georgia', value: 'Georgia', code: 'GE' },
  { name: 'Germany', value: 'Germany', code: 'DE' },
  { name: 'Ghana', value: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', value: 'Gibraltar', code: 'GI' },
  { name: 'Greece', value: 'Greece', code: 'GR' },
  { name: 'Greenland', value: 'Greenland', code: 'GL' },
  { name: 'Grenada', value: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', value: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', value: 'Guam', code: 'GU' },
  { name: 'Guatemala', value: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', value: 'Guernsey', code: 'GG' },
  { name: 'Guinea', value: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', value: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', value: 'Guyana', code: 'GY' },
  { name: 'Haiti', value: 'Haiti', code: 'HT' },
  {
    name: 'Heard Island and McDonald Islands',
    value: 'Heard Island and McDonald Islands',
    code: 'HM',
  },
  { name: 'The Holy See', value: 'The Holy See', code: 'VA' },
  { name: 'Honduras', value: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', value: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', value: 'Hungary', code: 'HU' },
  { name: 'Iceland', value: 'Iceland', code: 'IS' },
  { name: 'India', value: 'India', code: 'IN' },
  { name: 'Indonesia', value: 'Indonesia', code: 'ID' },
  { name: 'Iran (Islamic Republic of)', value: 'Iran (Islamic Republic of)', code: 'IR' },
  { name: 'Iraq', value: 'Iraq', code: 'IQ' },
  { name: 'Ireland', value: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', value: 'Isle of Man', code: 'IM' },
  { name: 'Israel', value: 'Israel', code: 'IL' },
  { name: 'Italy', value: 'Italy', code: 'IT' },
  { name: 'Jamaica', value: 'Jamaica', code: 'JM' },
  { name: 'Japan', value: 'Japan', code: 'JP' },
  { name: 'Jersey', value: 'Jersey', code: 'JE' },
  { name: 'Jordan', value: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', value: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', value: 'Kenya', code: 'KE' },
  { name: 'Kiribati', value: 'Kiribati', code: 'KI' },
  {
    name: "Korea (the Democratic People's Republic of)",
    value: "Korea (the Democratic People's Republic of)",
    code: 'KP',
  },
  { name: 'Korea (the Republic of)', value: 'Korea (the Republic of)', code: 'KR' },
  { name: 'Kuwait', value: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', value: 'Kyrgyzstan', code: 'KG' },
  {
    name: "The Lao People's Democratic Republic",
    value: "The Lao People's Democratic Republic",
    code: 'LA',
  },
  { name: 'Latvia', value: 'Latvia', code: 'LV' },
  { name: 'Lebanon', value: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', value: 'Lesotho', code: 'LS' },
  { name: 'Liberia', value: 'Liberia', code: 'LR' },
  { name: 'Libya', value: 'Libya', code: 'LY' },
  { name: 'Liechtenstein', value: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', value: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', value: 'Luxembourg', code: 'LU' },
  { name: 'Macao', value: 'Macao', code: 'MO' },
  { name: 'Madagascar', value: 'Madagascar', code: 'MG' },
  { name: 'Malawi', value: 'Malawi', code: 'MW' },
  { name: 'Malaysia', value: 'Malaysia', code: 'MY' },
  { name: 'Maldives', value: 'Maldives', code: 'MV' },
  { name: 'Mali', value: 'Mali', code: 'ML' },
  { name: 'Malta', value: 'Malta', code: 'MT' },
  { name: 'The Marshall Islands', value: 'The Marshall Islands', code: 'MH' },
  { name: 'Martinique', value: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', value: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', value: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', value: 'Mayotte', code: 'YT' },
  { name: 'Mexico', value: 'Mexico', code: 'MX' },
  {
    name: 'Micronesia (Federated States of)',
    value: 'Micronesia (Federated States of)',
    code: 'FM',
  },
  { name: 'Moldova (the Republic of)', value: 'Moldova (the Republic of)', code: 'MD' },
  { name: 'Monaco', value: 'Monaco', code: 'MC' },
  { name: 'Mongolia', value: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', value: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', value: 'Montserrat', code: 'MS' },
  { name: 'Morocco', value: 'Morocco', code: 'MA' },
  { name: 'Mozambique', value: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', value: 'Myanmar', code: 'MM' },
  { name: 'Namibia', value: 'Namibia', code: 'NA' },
  { name: 'Nauru', value: 'Nauru', code: 'NR' },
  { name: 'Nepal', value: 'Nepal', code: 'NP' },
  { name: 'The Netherlands', value: 'The Netherlands', code: 'NL' },
  { name: 'New Caledonia', value: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', value: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', value: 'Nicaragua', code: 'NI' },
  { name: 'The Niger', value: 'The Niger', code: 'NE' },
  { name: 'Nigeria', value: 'Nigeria', code: 'NG' },
  { name: 'Niue', value: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', value: 'Norfolk Island', code: 'NF' },
  { name: 'The Northern Mariana Islands', value: 'The Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', value: 'Norway', code: 'NO' },
  { name: 'Oman', value: 'Oman', code: 'OM' },
  { name: 'Pakistan', value: 'Pakistan', code: 'PK' },
  { name: 'Palau', value: 'Palau', code: 'PW' },
  { name: 'Palestine, State of', value: 'Palestine, State of', code: 'PS' },
  { name: 'Panama', value: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', value: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', value: 'Paraguay', code: 'PY' },
  { name: 'Peru', value: 'Peru', code: 'PE' },
  { name: 'The Philippines', value: 'The Philippines', code: 'PH' },
  { name: 'Pitcairn', value: 'Pitcairn', code: 'PN' },
  { name: 'Poland', value: 'Poland', code: 'PL' },
  { name: 'Portugal', value: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', value: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', value: 'Qatar', code: 'QA' },
  { name: 'Republic of North Macedonia', value: 'Republic of North Macedonia', code: 'MK' },
  { name: 'Romania', value: 'Romania', code: 'RO' },
  { name: 'The Russian Federation', value: 'The Russian Federation', code: 'RU' },
  { name: 'Rwanda', value: 'Rwanda', code: 'RW' },
  { name: 'Réunion', value: 'Réunion', code: 'RE' },
  { name: 'Saint Barthélemy', value: 'Saint Barthélemy', code: 'BL' },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    value: 'Saint Helena, Ascension and Tristan da Cunha',
    code: 'SH',
  },
  { name: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', value: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Martin (French part)', value: 'Saint Martin (French part)', code: 'MF' },
  { name: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon', code: 'PM' },
  {
    name: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
    code: 'VC',
  },
  { name: 'Samoa', value: 'Samoa', code: 'WS' },
  { name: 'San Marino', value: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', value: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', value: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', value: 'Senegal', code: 'SN' },
  { name: 'Serbia', value: 'Serbia', code: 'RS' },
  { name: 'Seychelles', value: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', value: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', value: 'Singapore', code: 'SG' },
  { name: 'Sint Maarten (Dutch part)', value: 'Sint Maarten (Dutch part)', code: 'SX' },
  { name: 'Slovakia', value: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', value: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', value: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', value: 'Somalia', code: 'SO' },
  { name: 'South Africa', value: 'South Africa', code: 'ZA' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
  },
  { name: 'South Sudan', value: 'South Sudan', code: 'SS' },
  { name: 'Spain', value: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', value: 'Sri Lanka', code: 'LK' },
  { name: 'The Sudan', value: 'The Sudan', code: 'SD' },
  { name: 'Suriname', value: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', value: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Sweden', value: 'Sweden', code: 'SE' },
  { name: 'Switzerland', value: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', value: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan (Province of China)', value: 'Taiwan (Province of China)', code: 'TW' },
  { name: 'Tajikistan', value: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', value: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', value: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', value: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', value: 'Togo', code: 'TG' },
  { name: 'Tokelau', value: 'Tokelau', code: 'TK' },
  { name: 'Tonga', value: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', value: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', value: 'Tunisia', code: 'TN' },
  { name: 'Turkey', value: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', value: 'Turkmenistan', code: 'TM' },
  { name: 'The Turks and Caicos Islands', value: 'The Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', value: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', value: 'Uganda', code: 'UG' },
  { name: 'Ukraine', value: 'Ukraine', code: 'UA' },
  { name: 'The United Arab Emirates', value: 'The United Arab Emirates', code: 'AE' },
  {
    name: 'The United Kingdom of Great Britain and Northern Ireland',
    value: 'The United Kingdom of Great Britain and Northern Ireland',
    code: 'GB',
  },
  {
    name: 'The United States Minor Outlying Islands',
    value: 'The United States Minor Outlying Islands',
    code: 'UM',
  },
  { name: 'USA', value: 'USA', code: 'US' },
  { name: 'Uruguay', value: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', value: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', value: 'Vanuatu', code: 'VU' },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    value: 'Venezuela (Bolivarian Republic of)',
    code: 'VE',
  },
  { name: 'Viet Nam', value: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands (British)', value: 'Virgin Islands (British)', code: 'VG' },
  { name: 'Virgin Islands (U.S.)', value: 'Virgin Islands (U.S.)', code: 'VI' },
  { name: 'Wallis and Futuna', value: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', value: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', value: 'Yemen', code: 'YE' },
  { name: 'Zambia', value: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', value: 'Zimbabwe', code: 'ZW' },
];

const USA_COUNTRY_OPTION = { label: 'USA', value: 'USA' };

export default {
  allCountryOptions,
  USA_COUNTRY_OPTION,
};
